name: explorenorth
favicon: null
layout_spectrum: 0.56236
typography_spectrum: 0.7935487048234791
title: Explore North
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: www.explorenorth.no
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101922'
    - '#6795c7'
    - '#8ab5df'
    - '#255273'
    - '#e2eced'
  brandStrength: 0.625
  lightness: 0.9957925654016435
  saturation: 0.375
  rhythmicContrast: 0.5549349139910191
purpose: []
