name: explorenorth
favicon: null
layout_spectrum: 0.56236
typography_spectrum: 0.7935487048234791
title: Explore North
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff8d00'
    - '#704b15'
    - '#d2c7b6'
    - '#947850'
  brandStrength: 0.5753322248347104
  lightness: 0.9957925654016435
  saturation: 0.375
  rhythmicContrast: 0.5549349139910191
purpose: []
